import { useState } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {

  const [account, setAccount] = useState('j')

  const myItems = new Array(20).fill('')

  return (
    <div className={styles.container}>
      <Head>
        <title>Celo Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <nav>
          <h1>Celo Market</h1>
          <>
           {!account ? <button>Connect wallet</button> : <Link href={'/post-item'}>New product</Link>  }
          </>
        </nav>

        <div className={styles.items}>
          {
            myItems.map(item => <div className={styles.item}>
              <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIe211cVjor6ImCg6L3MfUa9B9wgAKsQJp1Q&usqp=CAU" alt="" />
              <section>
                <h3>Nike Airforce</h3>
                <span>55$</span>
              </section>
              <button className={styles.delete}>Delete</button>
              <button>Buy</button>
            </div> )
          }
        </div>
      </main>

      
    </div>
  )
}
